version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "mambaforge-4.10"
  jobs:
    post_install:
    - conda env list
    - conda list
    - which python
    - which conda

conda:
  environment: docs/environment.yml

sphinx:
  fail_on_warning: false

formats: []
